// generated by Fast Light User Interface Designer (fluid) version 1.0300

#ifndef ConfigUI_h
#define ConfigUI_h
#include <FL/Fl.H>
#include <stdio.h>
#include <math.h>
#include <stdlib.h>
#include <FL/Fl_File_Chooser.H>
#include "Fl_Osc_Button.H"
#include "Fl_Osc_Counter.H"
#include "Fl_Osc_Choice.H"
#include "Osc_IntModel.h"
#include "Fl_Osc_Check.H"
#include "Fl_Osc_Input.H"
#include "Fl_Osc_Numeric_Input.H"
#include "Fl_Osc_ListView.H"
#include "Fl_Osc_Pane.H"
#include "../globals.h"
#include "../Misc/Util.h"
using namespace zyncarla;
#include <FL/Fl_Box.H>
#include <FL/Fl_Tabs.H>
#include <FL/Fl_Group.H>
#include <FL/Fl_Choice.H>
#include <FL/Fl_Button.H>

class ConfigUI {
public:
  Fl_Osc_Window* make_window();
  Fl_Osc_Window *configwindow;
private:
  void cb_configwindow_i(Fl_Osc_Window*, void*);
  static void cb_configwindow(Fl_Osc_Window*, void*);
public:
  Fl_Box *dummy;
  Fl_Group *mainsettings;
  Fl_Osc_Numeric_Input *samplerateinput;
  Fl_Choice *oscilsize_widget;
private:
  void cb_oscilsize_widget_i(Fl_Choice*, void*);
  static void cb_oscilsize_widget(Fl_Choice*, void*);
  static Fl_Menu_Item menu_oscilsize_widget[];
  static Fl_Menu_Item menu_PADsynth[];
  static Fl_Menu_Item menu_Virtual[];
public:
  Fl_Osc_ListView *rootsbrowse;
private:
  void cb_rootsbrowse_i(Fl_Osc_ListView*, void*);
  static void cb_rootsbrowse(Fl_Osc_ListView*, void*);
  void cb_Add_i(Fl_Button*, void*);
  static void cb_Add(Fl_Button*, void*);
public:
  Fl_Button *removerootdirbutton;
private:
  void cb_removerootdirbutton_i(Fl_Button*, void*);
  static void cb_removerootdirbutton(Fl_Button*, void*);
public:
  Fl_Button *makedefaultrootdirbutton;
private:
  void cb_makedefaultrootdirbutton_i(Fl_Button*, void*);
  static void cb_makedefaultrootdirbutton(Fl_Button*, void*);
public:
  Fl_Osc_ListView *presetbrowse;
private:
  void cb_presetbrowse_i(Fl_Osc_ListView*, void*);
  static void cb_presetbrowse(Fl_Osc_ListView*, void*);
  void cb_Add1_i(Fl_Button*, void*);
  static void cb_Add1(Fl_Button*, void*);
public:
  Fl_Button *removepresetbutton;
private:
  void cb_removepresetbutton_i(Fl_Button*, void*);
  static void cb_removepresetbutton(Fl_Button*, void*);
public:
  Fl_Button *makedefaultpresetbutton;
private:
  void cb_makedefaultpresetbutton_i(Fl_Button*, void*);
  static void cb_makedefaultpresetbutton(Fl_Button*, void*);
  void cb_Close_i(Fl_Button*, void*);
  static void cb_Close(Fl_Button*, void*);
public:
  ConfigUI(Fl_Osc_Interface *osc_);
  void activatebutton_rootdir(bool active);
  void activatebutton_presetdir(bool active);
  void show();
  class Fl_Osc_Interface *osc;
  class Osc_IntModel *oscilsize;
};
#endif
